### ISSUE TITLE
Ues feature extractor or weight generator for evaluation?

### ISSUE THREAD

**Issue by skyz8421** [bilylee/DCQ#4]
Hi, nice work about face recognition! I'm only confused about the following:
   
   In Section **3.1. Preliminaries Classification-based Representation Learning.**, as the paper says, "During evaluation, the FC layer is removed and only the **feature extractor** is used." 
  
But in the code https://github.com/bilylee/DCQ/blob/5422b636fd4e68339d1d2cd65c43f0f048255327/dcq.py#L146

It uses the weight generator network(**encoder_k**) to get the feature(or weight?) for evaluation; I am very puzzled here. Is there something that I missed?

**Comment by liubx07** [comment]
In fact, encoder_k is a moving averaged copy of the feature extractor, so the code here is right
